---
title: "Git ガイドライン"
created_at: 2016-05-12T00:00:00+0900
excerpt: "Git の使い方ガイドライン。"
kind: article
status: draft
htags:
  - ロ技研/ガイドライン/Git

---

:icons: font
:experimental:

== 概要

* Git とは何なのか学ぶ
* バージョン管理について学ぶ
* Git のある程度の使い方を学ぶ

== 本文
=== バージョン管理

バージョン管理とは、自分がプログラム（もっと平たく言ってしまえばテキストファイル）に加えた変更を記録していながら、変更の歴史を作っていくことです。手動でやるのはあまりに非効率的なので、Git という便利なツールを使います。 +
バージョン管理システムは、ある程度の規模があって、大きな変更を加える可能性のあるプロジェクトに対して有効です。 +

.「リモート」と「ローカル」
[NOTE]
バージョン管理システムで大事な概念は「リモート」と「ローカル」の2つです。簡単に説明すると、「ローカル」は手元のマシン、「リモート」はサーバーとなります。ローカルで編集した内容をリモートに置くことによってローカルとの差分を見ながらバージョン管理します。

.gitとGitHubの違い
[NOTE]
link:https://git-scm.com/[Git] はバージョン管理システムであり、link:https://github.com/[GitHub] はウェブサービスです。Git のホスティングサービスとしては GitHub が有名で、他には link:https://ja.atlassian.com/software/bitbucket[bitbucket] などがありますが、弊サークルでは GitHub を使っていきます。

=== Git のインストール

==== Mac

まずは link:http://brew.sh/index_ja.html[Homebrew] というパッケージマネージャーをインストールしましょう。 コマンド1つでインストール出来ます。

.Homebrew のインストール
----
$ /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
----

念のためバージョンを確認してインストールが成功したかどうかチェックしましょう。

.Homebrew のバージョン確認
----
$ brew --version
----

以下の様になったら成功しています。

.Homebrew のバージョン確認の結果
----
Homebrew 0.9.9 (git revision 2f20a; last commit 2016-05-15)
Homebrew/homebrew-core (git revision 2fd046; last commit 2016-05-17)
----

Mac は標準で git がインストールされていますが、念のため Homebrew でインストールしておきます。

.Git のインストール
----
$ brew install git
----

バージョンを確認して以下の様になったら成功しています。

.Git のバージョン確認
----
$ git --version
git version 2.8.2
----

しかし、Git をインストールしただけではアカウントがないのでコミット出来ません。次にアカウントを作りましょう。

==== Linux

===== ソースからのインストール

Gitをインストールするためには、Gitが依存するライブラリーである、curl、zlib、openssl、expat、libiconvを入手する必要があります。
例えば、もし（Fedoraなどで）yumか（Debianベースのシステムなどで）apt-getが入ったシステムを使っているのであれば、これらのコマンドの一つを依存対象の全てをインストールするのに使う事ができます。

.依存ライブラリのインストール
-----
$ yum install curl-devel expat-devel gettext-devel \
  openssl-devel zlib-devel

$ apt-get install libcurl4-gnutls-dev libexpat1-dev gettext \
  libz-dev libssl-dev
-----

もし Fedora を使っているのなら `yum` が使えます。

.Linux へのインストール (`yum`)
----
$ yum install git
----

Ubuntu のような Debian ベースのディストリビューションなら `apt-get` が使えます。

.Linux へのインストール (`apt-get`)
----
$ apt-get install git
----


詳しくは
link:https://git-scm.com/book/ja/v1/%E4%BD%BF%E3%81%84%E5%A7%8B%E3%82%81%E3%82%8B-Git%E3%81%AE%E3%82%A4%E3%83%B3%E3%82%B9%E3%83%88%E3%83%BC%E3%83%AB[Git公式ドキュメント]
を参照してください。

==== Windows

=== GitHub アカウント作成手順

. link:https://github.com/[GitHub] のサイトにアクセス
. 必要事項を記入
.. ID、メールアドレス、パスワードを入力して「Sigh up for GitHub」をクリック
. 確認メール
.. 登録したメールアドレスに確認メールが来るので、メールを開き、その中にある「verify email address」ボタンを押す
.. 「Welcome to GitHub!」なるメールが来たら登録完了

=== GitHub チュートリアル

==== アカウント設定

ローカルにも git の設定を適用させましょう。 +
ホームディレクトリに `.gitconfig` というファイルを作って以下のように書いてください。
----
$ vi .gitconfig
[user]
  name = [account name]
  email = [mail address]
[push]
  default = simple
----
[NOTE]
[account name] は登録したアカウント名を、[mail address] は登録したメールアドレスを記入してください。そのとき `[ ]` は付けないように注意してください。

==== リポジトリを作る

Git はリポジトリという単位でプロジェクト（簡単に言うとファイル群）を管理します。まず、git で管理したいディレクトリに移動します。そして、 git でファイルを管理するように認識させるように `$ git init` します。
----
$ cd /path/to/directory
$ git init
----
これでカレントディレクトリ以下を git で管理出来るようになりました。この git で管理されているディレクトリのことを *リポジトリ* といいます。このディレクトリには `.git` というディレクトリが作成されます（`ls -A` で確認出来ます）。これは git が情報を保存するためのディレクトリであり、基本的にこのディレクトリを編集することはあまりありません。

==== add して commmit して push

ここから Git の基本的な使い方を説明します。 +
まず、あなたがあるファイルに変更を加える（例えばファイルに記述を足したり減らしたり、ファイルを作ったり削ったりする）とします。それをどのようにして Git に追跡させたらいいでしょうか。 +
使うコマンドは簡単で、変更したファイルを `add` すればよいです。 +
例えば、 `hoge.scala` というファイルを作ってファイルにソースを書き込んだとします。 +
`$ git status` してみてください。すると、あなたの変更がちゃんと `Git` に伝わっていれば次のように表示されるはずです。

----
modified: hoge.scala
----

これを `add` しましょう。

----
$ git add hoge.scala
----

そして `commit` です。ちなみに `$ git commit` にはいくつかオプションがあり、よく使われるのは `-m` オプションです。次のように打つと `""` で囲まれた部分がコミットメッセージとして記録されます。

----
$ git commit -m "commit message"
----

もちろん `$ git commit` だけでもよいです。この場合 `vim` か `emacs` が立ち上がってコミットメッセージの編集が行われます。

そして `push` といきたいところですが、ここで今までの作業がちゃんと `Git` に対して伝わっているかチェックしましょう。チェックするためのコマンドは、先ほど使った `$ git status` で行えます。 `$ git status` してちゃんとステージング（`push` でリモートにアップさせる前の段階）に上がっているか確認しましょう。 +
さらに、 `$ git log` をすればコミットログを見れるので、参考までに覚えておきましょう。 +
では、最後にリモートに `push` しましょう。 +

----
$ git push -u origin master
----

`push` したあと、`GitHub` のサイトにいってちゃんと `push` できているか確認してみてください。

これで基本的な流れは解説しました。他にも `branch` や `rebase` などといった機能があり、チーム開発には必須のコマンドです。次では `branch` について説明しますので、よく読んでおいてください。
