:source-highlighter: coderay
//ソースコードのハイライトを有効化
:icons: font
//NOTEなどのアイコンを有効化

= 5月部会
:Author:    Takahiro Ishihara
:Email:     <mrx0806@gmail.com>
:Date:      2017/5/24
:Revision:  1.0

== rogyゼミ係
16の人3人にrogyゼミ係をやってほしいです.
突然なので決まらなければ6月部会の時に.

== f3rc領域
f3rc領域を確保しました. +
2つは空いている箱ですが, 1つは郵便領域との共用なので注意してください.

== 第二部室と教室予約について
=== 第二部室について
先のMLに流した通り第二部室を確保しました. +
自由に使ってもらってかまわないですが, 最後に退出する人は消灯とエアコンを消すことは忘れないでください.

=== 教室予約について
17も含めサークル活動で必要ならば教室予約をしてもらって構いません. +
予約方法は教務webシステムの講義室予約のページからできます. + +
毎月10日の深夜0時に翌月の教室予約が始まるのでその時に予約しないと良い教室は取れなかったりします. +
その後, 3営業日前までに教務課に講義室予約申請書を提出してください. + +
また休日に予約する際は守衛から鍵を借りないと部屋に入れません. +
教室予約した際は副部長に連絡してください.

== 部室宛荷物について
サークル活動に必要なものならばサークル宛に荷物を送ってもらって構いません. +
住所は "東京都目黒区大岡山2-12-1サークル棟4-436号室" で宛名には "ロボット技術研究会 + (自分の名前)" を含めるようにしてください. +
サークル宛荷物は部室に届く以外にも, W9の支援課の所にも届きます. +
大きい荷物はトレーではなく机の上に置かれますが, それを回収した際はトレーについてある荷札みたいなものをきちんと元の場所に戻すようにしてください.  +
また, 他人の荷物などを回収した場合には部室奥の郵便領域に入れておいてください. +
あと注意事項として重い物や壊れ物はレターパックで送ることのないようにしてください(支援課のヒスBBAがブチ切れてた).

== 部費について
部費について色々思っている人がいるかと思うので伝えておきます. +
収入200万で支出160万.支出は工作系35%,電子系23%,イベント21%,システム11%と言った感じ. +
工作系は工作機械に20万で材料費に30万と言った感じ.電子系は全部消耗品で37万.イベントはコミケやF3RC,ミニコン,Make,工大祭,新歓などで34万. +
工作機械や電子部品を使わない人にとっては部費が高いという話. +
じゃぁそれらを使わない人は部費を下げる?→逆に部費を安くするために機械工作や電子工作をしないみたいな風潮が生まれるのはどうなのって思ったり. +
消耗品は自腹にする→具体的な徴収方法はどうするのか. +
あと最近部員数は多いけど, 部員数が少なる可能性があることも念頭にある程度の余裕はほしいよね. +
5月部会で何か議決するという気はないけど, 何かいいやり方なり意見なりがあったら言ってください. 6月部会の時に議論をするかも? +

== NHK学生ロボコン
=== 観戦はがき
余分に当たったなどの不要な観戦はがきがあれば部会後に山田さんまで渡してください.

=== 観戦
6/11(日)に行われます. 観戦はがきがないけど見に行きたいなどあれば山田さんまで.

== 今後の予定
=== 日程調査
7月部会と前期研究報告会の日程調査を行っているので各位は回答してほしいです.

=== 講習会
2Qからはマイコン講習会とCAD講習会が始まります.

=== 6月部会
- 6/19(月) 17:00~ W241
- パンフ係と立て看板係の引き継ぎを行います.

== その他
何かあれば.

=== 部費の支払い
会計に部費を払いましょう!

== この教室について
この教室の予約は14:50まで. ただS511~S513を終日確保しているのでそちらは使えます.
