:icons: font
//NOTEなどのアイコンを有効化

= 7月部会
:Author:    Takahiro Ishihara
:Email:     <mrx0806@gmail.com>
:Date:      2017/6/19
:Revision:  1.0

== 係決め
アンケート係(3人), 吊りパネル係(3人) +

== 倉庫について
部室横の支援課倉庫と1階の支援課倉庫が使えるようになりました. +
使うには支援課に行って鍵を借りる必要があります. 借りた際には借りた趣旨を部室の奥のホワイトボードに学年と氏名とともに記載して, 支援課が閉まる前まで(17時)に返却してください. +
f3rc機体やその他製作物をおいてもらって構いません. +

== f3rcとミニコン
ミニコンが9/19~24のどこかのタイミングで開催されます. 日程が決まっていないのは教室予約は8/10にならないと決まらないため. +
ルールはf3rcと同じ. f3rc参加者の皆さんは参加してもらうことになると思います. その他の学年の人もできれば参加しましょう! +

== 17部室利用規則
f3rc各チームに鍵を配布しました. 鍵は夏休みまでは使わないようにしてください. すなわち17の部室利用規則は夏休みまでは今までと同じです(17単独で部室にいてはいけない). +
夏休みからは17でも複数人が部室にいるようであれば, 17だけで部室にいてもらって構いません. +
ただし, 安全に十分に気をつけてください. 特に部室携帯が入って左の机の回路領域の棚のところにあるので確認しておいてください. +
また部室泊はダメです. +

== 部室キーボード
どうでもいい話. 今のPCについている部室のキーボード糞雑魚だけど変えたくないですか? +
キーボードはピンキリなので3000円付近の中華メカニカル, 1万円代近傍のメカニカル, 2万円代のReal forceどれがいいですか?

== 部室利用について
クッションを新しく買いました. 今はまだふかふか. あとホワイトボードにいろいろつけた. +
あったほうが良さそうなものがあったら言ってください. +
また部室奥に掃除機があるので気が向いたら掃除機をかけるようにしましょう. 3日ぐらいに1回ぐらいの頻度でかけても, 結構ほこりがでてくる. +
それと, 部室のゴミ箱がいっぱいになったら捨てに行きましょう! 捨てる場所は体育館裏のゴミ捨て場です. 白が可燃で青が不燃で黄色が缶です. あたらしい袋は工作領域の入って左側の気持ち高めのところの段においてあります.

== †社会貢献のチャンス†
http://www.titech.ac.jp/enrolled/news/2017/038487.html +
もう終わったけど小中高生向けにhogehoge教室やるなら金だすよみたいな話. +
1件50万なので, マインドストームとか適当なキット化ってロボット教室することはできそう. やりたい? +
今期の募集は終わったけど, 冬にまた募集するっぽい.

== 合宿について
合宿係から.

red 1man