---
title: "FBX 7.4/7.5 構造解説"
created_at: 2016-05-10T18:40:44+0900
excerpt: "FBX 7.4/7.5 の内部データ構造(スキーマ)について解説。未完成。"
kind: article
status: draft
htags:
  - "仕様解説/ファイル形式/FBX"
---

[WARNING]
.不完全なドキュメント
このドキュメントは不完全である。
そのうち書き足したい。

[IMPORTANT]
.「プロパティ」という言葉について
====
構造の解説でも「プロパティ」という言葉が利用されるかもしれないが、これは link:../syntax/binary#node-proprty[_node property_] とは異なる概念であることに留意せよ。
__node property__とはノードに付随するデータのことであったが、
以下、構造の解説の文書中での「プロパティ」とは、 `"P"` などの名前のノードで表現される、型やフラグを持ったデータのこととする。

これらを区別するため、 `"P"` などの名前のノードを「Pノード」等と呼ぶことがある。

====


[[abstract]]
== 概要
FBXファイルは木構造でデータを保持する。
しかし、この木構造は、3Dコンテンツの具体的な構成要素に見出される木構造(実際には有向非巡回グラフ)とは直接には無関係である。 +
具体的に言うと、ボーンの木構造(スケルトン)などはFBXの文法レベルの木構造では表現されない。

[NOTE]
.意味レベルでの木構造を見るには
手前味噌になるが、FBXを読まんとする辛い道程にて生まれたツール
link:https://github.com/l1048576/fbx_objects_depviz[l1048576/fbx_objects_depviz: FBX objects (nodes) dependency visualizer]
のREADMEに幾つかサンプルの画像を載せてあるので、実際どのような構造が利用されているのか見たければ、そちらを参照されたい。

意味レベルでの実際の木構造(グラフ)はどのように表現されるかというと、**ノードの配列**と**辺の配列**が別々の(構文レベルでの)ノードとして用意されている。
ノードの配列が xref:objects[] 、辺の配列が xref:connections[] だ。

それ以外の(構文レベルでの)ノードが何を持っているかというと、主にファイルやコンテンツのメタデータか、(構文レベルでの)ノードそのものについてのメタデータである。


[[top-structure]]
== トップの構造
[options="header", cols="4,>1,5"]
|====
| ノード名              | 出現      | 詳細
| `FBXHeaderExtension`  | 必須？    | ファイルのメタデータを持つ
| `FileId`              | 任意      | 謎の固定長バイト列。**生成規則は不明**
| `CreationTime`        | 必須      | ファイルの作成日時の文字列表現
| `Creator`             | 必須？    | FBXファイルの生成に利用されたツールを示す文字列
| `GlobalSettings`      | 必須？    | 軸の向きなど、データ全体で利用されるプロパティ群
| `Documents`           | 任意      | **詳細不明**。ひとつのFBXファイルに複数のシーンを含むためのものか？
| `References`          | 必須？    | **詳細不明**。__node property__・子ノードともに空のものしか見たことがない
| `Definitions`         | 任意      | xref:template[] の定義
| `Objects`             | 任意      | FBXの(意味レベルでの)グラフのノードの配列
| `Connections`         | 任意      | FBXの(意味レベルでの)グラフの辺の配列
| `Takes`               | 任意      | **詳細不明**。アニメーション関係のデータだろうか？
|====


[[fbxheaderextension]]
=== FBXHeaderExtension

// TODO: あとで書く
[NOTE]
.あとで書く
見ればわかる。あとで書く


[[fileid]]
=== FileId
__node property__として16バイトのバイナリデータを1つだけ持つ。
子ノードは無し。

16バイトのバイナリデータの詳細は不明。

FBX SDKのサンプルのmakefileにはリンク時の `-luuid` オプションの指定があったが、これがなくても正しく動作する。
よって、間接的に関係があるのかさえ不明。 +
また、7バイト目がc9である場合を観測したので、uuidである可能性はないだろう。
(uuidであれば、7バイト目の上位4ビットは1〜5でバージョン番号になる。)

参考までに、以下にこれまでFBX SDKから出力した、または公式な製品から出力されたと思われるもののFileIdを列挙しておく。

// NOTE: 以下のものは、NakanoSisters 1.1と1.2、それからFBX SDKで生成したファイルから抽出したものである。たぶん。

.FBX7.4
----
2d b0 28 ea b6 26 cc c1 bb ce b5 26 a3 24 f3 ff
2a b1 28 e1 bf 2d c5 c9 b0 c7 bc 2f aa 2d fe f0
2b b6 2f e6 b8 2a c2 ce b6 c7 bc 2f aa 2d ff f4
29 b7 2e e9 b5 24 cc c7 b3 c0 bb 28 ad 2a ff f7
2a b2 2b ec b0 21 c9 c2 be c1 ba 29 ac 2b fe f5
----

.FBX7.3
----
28 b5 2c e5 b8 2c c6 cc b7 c7 bc 2f aa 2d fa f0
29 b6 2f e6 bb 2f c5 cf b5 c7 bc 2f aa 2d fa f1
29 b0 29 ee b2 23 cb c0 bf cb b0 23 a6 21 f4 ff
2d b5 2c eb b7 26 ce c5 bc cf b4 27 a2 25 f0 f9
----

.バージョン忘れた
----
2d b3 2b eb b6 23 ca c2 bf c8 b3 20 a5 22 f5 f9
2b b9 21 e1 bc 28 c1 c9 b4 c3 b8 2b ae 29 fc f8
2a b7 2f ef b2 26 cf c7 ba cd b6 25 a0 27 f2 f8
29 b0 28 e8 b5 21 c8 c0 bd ca b1 22 a7 20 f5 f1
2a b4 2c ec b1 25 cc c4 b9 ce b5 26 a3 24 f1 f5
----

いずれのオクテットも上位4ビットが固定なのが手掛かりになりそうだが、今のところ生成規則は不明である。
少なくとも規則性は見られるから、完全な乱数ではないということだけはわかる。

各オクテットの上位4ビットが固定の16バイトの謎のバイナリは、 link:../syntax/binary#file-footer-1[ファイル自体のフッタ] にも現れるが、関係があるかは不明。


[[definitions]]
== Definitions
xref:template[] の配列。

[[template]]
=== Template
各Templateの実体は、 `Definitions` ノードの子ノードである `ObjectType` ノードである。

`ObjectType` の構造は以下の通り。

.`ObjectType` ノードの構造
[options="header", cols="2,7"]
|====
| 子ノード              | 詳細
| `Count`               | このTemplateを利用しているオブジェクトの個数。(要するにreference countのようなものだろう。)
| `PropertyTemplate`    | プロパティ(`Properties70` ノード)を保持する。
|====


[[objects]]
== Objects
`NodeAttributes`, `Deformer`, `Geometry`, `Material`, `Pose`, `Texture`, `Video` 等を子ノードに持つ。

`Geometry` ノードのうち、2番目の__node property__が `"\\x00\\x01Geometry"` で終わり、かつ3番目の__node property__が `"Mesh"` であるものがメッシュのようだ。

// TODO: あとで書く
[NOTE]
.あとで書く
子ノードについて書くと分量が多くなるので、そのうち別ページで書く

// TODO: このセクションもそのうち移動するので、IDは振らないでおく。
//[[objects-geometry-polygonvertexindex]]
=== PolygonVertexIndex
ひとつひとつの面(face)をつくる頂点のインデックスを持つ。
三角形以外も有り得るので、面の区切りをわかるようにするため、各面の最後のインデックスはビット反転(C言語風に書くなら、 `a` であれば `~a`)される。
link:http://wiki.blender.org/index.php/User:Mont29/Foundation/FBX_File_Structure#Mesh_Data[User:Mont29/Foundation/FBX File Structure - BlenderWiki] には以下のように記されている:

____
Polygons (defined by vertices indices, the last index of a polygon is negated).
____

この 'negate' は符号反転ではなくビット反転であることに留意せよ。

[NOTE]
.#それはそう
というか符号反転だと、面の途中の0と面の終わりの0の区別がつかなくなってしまうので、少し考えればわかることである。


[[connections]]
== Connections
xref:objects[] のノード同士を繋ぐ、(グラフ構造で言うところの)**辺**である、 xref:connections-c-node[`C` ノード]を子に持つ。

[[connections-c-node]]
=== `C` ノード
__node property__を3つか4つ持つ。

. xref:connections-c-node-property-1[ノード同士の関係]
. 辺のhead側のノードのID
. 辺のtail側のノードのID
. ノードの一方が属性の場合のみ存在？: 属性の名前

(意味上の)暗黙のルートノードのIDは0である。

[NOTE]
.headとtail
head→tail +
やで。

[[connections-c-node-property-1]]
==== ノード同士の関係
`"OO"`, `"OP"`, `"PO"`, `"PP"` のいずれかのはずである。
大抵は `"OO"` か `"OP"` である。


[[references]]
== 参考文献
- link:https://code.blender.org/2013/08/fbx-binary-file-format-specification/[FBX binary file format specification | Blender Code]
- link:http://wiki.blender.org/index.php/User:Mont29/Foundation/FBX_File_Structure[User:Mont29/Foundation/FBX File Structure - BlenderWiki]
- link:https://banexdevblog.wordpress.com/2014/06/23/a-quick-tutorial-about-the-fbx-ascii-format/[A quick tutorial about the FBX ASCII format | Banex Developer Blog on WordPress.com]
