---
title: "FBX 7.4/7.5 構文解説"
created_at: 2016-05-10T18:40:44+0900
excerpt: "FBX 7.4/7.5 の仕様について解説。"
kind: article
htags:
  - "仕様解説/ファイル形式/FBX"
---

FBX形式の構文についての解説。

[[tree-structure]]
== 木構造
FBXは(ヘッダ・フッタを除けば)木構造から成る。

ファイル自体は(XMLとは異なり)トップレベルに複数のノードを持つ(かのように見える)。
ただし、それらのノード全体を子として持つ、暗黙のルートノードが存在すると考えるのがよい。

ルートノードは名前を持たず(空文字列と考えてよい)、__node property__も持たず、子ノードのみを持つようなノードとして考える
footnote:[別ページの link:binary#implicit-root-node[暗黙のルートノード] 節を参照のこと]
。

[NOTE]
.暗黙のルートノード
__Binary FBX__において、暗黙のルートノードの存在を示唆するような構造が現れる
footnote:[別ページの link:binary#structure-overall[ファイル全体の構造] 節を参照のこと]
。

[[node]]
=== ノード
ノードは、以下の情報を持つ。

[options="header"]
|====
| 情報              | 型                        | 出現回数
| ノード名          | 文字列                    | 1
| _node property_   | __node property__型(後述) | 0以上
| 子ノード          | ノード                    | 0以上
|====

__node property__については後述するが、真偽値やfloatの配列など様々な型が有り得る。

[[node-property]]
=== _Node property_
__node property__というのは正式な名称ではない。
FBX SDKではこれを解釈した後の情報しか構造体で表現されないようで、名称をドキュメント中に発見できなかった。

__node property__は、ノードそのものに結び付く、XMLで言うところの属性のようなものである。

[NOTE]
.ノードの属性
「属性」(attribute)と呼ばないのには理由があって、FBX SDKにおいて__Node attribute__というと、
もっと具体化された情報を指しているからである
footnote:[link:++http://help.autodesk.com/view/FBX/2016/ENU/?guid=__cpp_ref_class_fbx_node_attribute_html++[Help: FbxNodeAttribute Class Reference], 2015/12/31参照]
。

[WARNING]
.プロパティ
====
FBX SDKにおいて「プロパティ」(property)という言葉は、ノードと__node property__によって表現される別の(具体的な)概念を指している
footnote:[link:++http://help.autodesk.com/view/FBX/2016/ENU/?guid=__cpp_ref_class_fbx_property_html++[Help: FbxProperty Class Reference], 2015/12/31参照]
。
これはシリアライズにおいての構造ではなく、3Dコンテンツとして解釈した際に見える構造であるから、
似た言葉ではあるが文脈から適切に判断できるだろう。

ただ、ややこしいのは確かであるから、解釈された概念としてのものを__Propertyノード__と呼び区別することにする。
(これはFBX 6では `Properties60` 、FBX 7では `Properties70` 等の名前のノードの子ノードであり、
`P` という名前のノードであるから、__Pノード__と呼ぶ場合もある。)

なお、__property node__という言葉は、
link:https://code.blender.org/2013/08/fbx-binary-file-format-specification/#property-record-format[FBX binary file format specification | Blender Code] (2015/12/31参照)
を参考にした。

====

[[types-of-node-property]]
==== __Node property__の値の型

__node property__は、ノード自体に属する情報として配列のように保持されるが、
それぞれが独立に以下の型のいずれかである。
(すなわち、配列の要素たる__node property__はそれぞれが別の型をとりうる。)

- プリミティブ型
  * 1バイト論理値
  * 2バイト符号付き整数
  * 4バイト符号付き整数
  * 8バイト符号付き整数
  * 4バイト単精度浮動小数点数 (IEEE 754)
  * 8バイト単精度浮動小数点数 (IEEE 754)
- 配列型
  * 1バイト論理値の配列
  * 4バイト符号付き整数の配列
  * 8バイト符号付き整数の配列
  * 4バイト単精度浮動小数点数 (IEEE 754) の配列
  * 8バイト単精度浮動小数点数 (IEEE 754) の配列
- 特殊型
  * 文字列
  * バイナリデータ (raw binary data)

[NOTE]
.型の呼称
プリミティブ型、配列型、特殊型という名称は
link:https://code.blender.org/2013/08/fbx-binary-file-format-specification/#property-record-format[FBX binary file format specification | Blender Code] (2015/12/31参照)
を参考にした。

[TIP]
.embedded textures
====
バイナリデータを持てることから推測できるが、FBXファイルにはテクスチャ等の画像データを埋め込み
footnote:[link:http://download.autodesk.com/us/fbx/20112/FBX_SDK_HELP/index.html?url=WS1a9193826455f5ff7b1de9f8127315f1b54-5a50.htm,topicNumber=d0e1054[Autodesk FBX SDK Progammer's Guide: Texture file formats embedded or referenced], 2015/12/31参照]
、単独のファイルで全てのリソースを保持することもできる。

ただしこれは、__FBX Binary__限定の機能である。

更に、FBX SDKでテクスチャの埋め込まれたFBXファイルを読んだ場合、FBXファイルと同じディレクトリに新たなディレクトリが作られ、
その中にテクスチャファイルが展開される。
(たとえば `foo.fbx` であれば、 `foo.fbm` というディレクトリが生成され、その中にテクスチャが展開される。)
ファイルを閉じてもそのディレクトリは削除されない。

====
